name: test_project
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  cached_network_image: ^3.2.3
  calendar_date_picker2: ^0.5.3
  charts_flutter_new: ^0.12.0
  conditional_builder_null_safety: ^0.0.6
  dartz: ^0.10.1
  dio: ^5.3.2
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_advanced_switch: ^3.0.1
  flutter_bloc: ^8.1.3
  flutter_native_splash: ^2.3.3
  flutter_remix: ^0.0.3
  flutter_screenutil: ^5.8.4
  flutter_svg: ^2.0.7
  fluttertoast: ^8.2.2
  geolocator: ^10.0.0
  get_it: ^7.6.4
  google_fonts: ^5.1.0
  google_maps_flutter: ^2.4.0
  image_picker: ^1.0.3
  json_annotation: ^4.8.1
  lottie: ^2.6.0
  map_launcher: ^2.5.0+1
  shared_preferences: ^2.2.1
  shimmer: ^3.0.0
  sms_autofill: ^2.3.0
  url_launcher: ^6.1.12

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/lottie/
    - assets/svg/
    - assets/json/
